version: '3.4'

services:
    catalogdb:
        image: mongo

    productcatalog.api:
        image: ${DOCKER_REGISTRY-}productcatalogapi
        build:
            context: .
            dockerfile: src/Services/ProductCatalog/ProductCatalog.Api/Dockerfile
