const ProductActionTypes = {
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_CATEGORY_PRODUCTS: 'GET_CATEGORY_PRODUCTS',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR'
};

export default ProductActionTypes;